<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_video extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Kategori_video_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $kategori_video = $this->Kategori_video_model->get_all();
        $data = array(
            'kategori_video_data' => $kategori_video,
        );
        $this->template->load('template','kategori_video/kategori_video_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Kategori_video_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
		'kategori_video_id' => $row->kategori_video_id,
		'nama_kategori_video' => $row->nama_kategori_video,
	    );
            $this->template->load('template','kategori_video/kategori_video_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_video'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kategori_video/create_action'),
	    'kategori_video_id' => set_value('kategori_video_id'),
	    'nama_kategori_video' => set_value('nama_kategori_video'),
	);
        $this->template->load('template','kategori_video/kategori_video_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kategori_video' => $this->input->post('nama_kategori_video',TRUE),
	    );

            $this->Kategori_video_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kategori_video'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kategori_video_model->get_by_id(decrypt_url($id));

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kategori_video/update_action'),
		'kategori_video_id' => set_value('kategori_video_id', $row->kategori_video_id),
		'nama_kategori_video' => set_value('nama_kategori_video', $row->nama_kategori_video),
	    );
            $this->template->load('template','kategori_video/kategori_video_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_video'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kategori_video_id', TRUE));
        } else {
            $data = array(
		'nama_kategori_video' => $this->input->post('nama_kategori_video',TRUE),
	    );

            $this->Kategori_video_model->update($this->input->post('kategori_video_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kategori_video'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kategori_video_model->get_by_id(decrypt_url($id));

        if ($row) {
            $this->Kategori_video_model->delete(decrypt_url($id));
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kategori_video'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_video'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kategori_video', 'nama kategori video', 'trim|required');

	$this->form_validation->set_rules('kategori_video_id', 'kategori_video_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kategori_video.php */
/* Location: ./application/controllers/Kategori_video.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-19 07:13:06 */
/* http://harviacode.com */