<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_modul extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Kategori_modul_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $kategori_modul = $this->Kategori_modul_model->get_all();
        $data = array(
            'kategori_modul_data' => $kategori_modul,
        );
        $this->template->load('template','kategori_modul/kategori_modul_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Kategori_modul_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
		'kategori_modul_id' => $row->kategori_modul_id,
		'nama_kategori_modul' => $row->nama_kategori_modul,
	    );
            $this->template->load('template','kategori_modul/kategori_modul_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_modul'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kategori_modul/create_action'),
	    'kategori_modul_id' => set_value('kategori_modul_id'),
	    'nama_kategori_modul' => set_value('nama_kategori_modul'),
	);
        $this->template->load('template','kategori_modul/kategori_modul_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kategori_modul' => $this->input->post('nama_kategori_modul',TRUE),
	    );

            $this->Kategori_modul_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kategori_modul'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kategori_modul_model->get_by_id(decrypt_url($id));

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kategori_modul/update_action'),
		'kategori_modul_id' => set_value('kategori_modul_id', $row->kategori_modul_id),
		'nama_kategori_modul' => set_value('nama_kategori_modul', $row->nama_kategori_modul),
	    );
            $this->template->load('template','kategori_modul/kategori_modul_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_modul'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kategori_modul_id', TRUE));
        } else {
            $data = array(
		'nama_kategori_modul' => $this->input->post('nama_kategori_modul',TRUE),
	    );

            $this->Kategori_modul_model->update($this->input->post('kategori_modul_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kategori_modul'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kategori_modul_model->get_by_id(decrypt_url($id));

        if ($row) {
            $this->Kategori_modul_model->delete(decrypt_url($id));
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kategori_modul'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_modul'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kategori_modul', 'nama kategori modul', 'trim|required');

	$this->form_validation->set_rules('kategori_modul_id', 'kategori_modul_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kategori_modul.php */
/* Location: ./application/controllers/Kategori_modul.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-19 07:13:03 */
/* http://harviacode.com */