<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Modul_pdf_model extends CI_Model
{

    public $table = 'modul_pdf';
    public $id = 'modul_pdf_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kategori_modul', 'kategori_modul.kategori_modul_id = modul_pdf.kategori_modul_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('modul_pdf_id', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('author', $q);
	$this->db->or_like('tahun_terbit', $q);
	$this->db->or_like('file_pdf', $q);
	$this->db->or_like('kategori_modul_id', $q);
	$this->db->or_like('view', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Modul_pdf_model.php */
/* Location: ./application/models/Modul_pdf_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-19 10:51:13 */
/* http://harviacode.com */