<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Video_model extends CI_Model
{

    public $table = 'video';
    public $id = 'video_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kategori_video', 'kategori_video.kategori_video_id = video.kategori_video_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('video_id', $q);
        $this->db->or_like('title', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('kategori_video_id', $q);
        $this->db->or_like('link_url', $q);
        $this->db->or_like('view', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Video_model.php */
/* Location: ./application/models/Video_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-19 10:42:24 */
/* http://harviacode.com */